<?php

namespace ContainerWJBtpbO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_TJ4hCMfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.TJ4hCMf' shared service.
     *
     * @return \App\Controller\Product
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ProduitController::addToFavorites()": the $product argument is type-hinted with the non-existent class or interface: "App\\Controller\\Product". Did you forget to add a use statement?');
    }
}
