<?php

namespace ContainerOvHvtxq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JSh55G8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JSh55G8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JSh55G8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailerService' => ['privates', 'App\\Service\\MailerService', 'getMailerServiceService', true],
            'ordersRepository' => ['privates', 'App\\Repository\\OrdersRepository', 'getOrdersRepositoryService', true],
        ], [
            'entityManager' => '?',
            'mailerService' => 'App\\Service\\MailerService',
            'ordersRepository' => 'App\\Repository\\OrdersRepository',
        ]);
    }
}
