<?php

namespace ContainerOvHvtxq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ET8b3QWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ET8b3QW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ET8b3QW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'orderInformation' => ['privates', '.errored..service_locator.ET8b3QW.App\\Entity\\OrderInformations', NULL, 'Cannot autowire service ".service_locator.ET8b3QW": it needs an instance of "App\\Entity\\OrderInformations" but this type has been excluded in "config/services.yaml".'],
        ], [
            'orderInformation' => 'App\\Entity\\OrderInformations',
        ]);
    }
}
