<?php

namespace ContainerOvHvtxq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2SlAymHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2SlAymH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2SlAymH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'product' => ['privates', '.errored..service_locator.2SlAymH.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.2SlAymH": it needs an instance of "App\\Entity\\Produit" but this type has been excluded in "config/services.yaml".'],
        ], [
            'product' => 'App\\Entity\\Produit',
        ]);
    }
}
