<?php

namespace ContainerOvHvtxq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderInformationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ET8b3QW.App\Entity\OrderInformations' shared service.
     *
     * @return \App\Entity\OrderInformations
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ET8b3QW": it needs an instance of "App\\Entity\\OrderInformations" but this type has been excluded in "config/services.yaml".');
    }
}
