<?php

namespace ContainerRxzOhNr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PViCr1XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PViCr1X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PViCr1X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'snappy' => ['services', 'knp_snappy.pdf', 'getKnpSnappy_PdfService', true],
            'twig' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'reclamationRepository' => 'App\\Repository\\ReclamationRepository',
            'snappy' => '?',
            'twig' => '?',
        ]);
    }
}
