<?php

namespace ContainerNi7xDEk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaiementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VxAVubp.App\Entity\Paiement' shared service.
     *
     * @return \App\Entity\Paiement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VxAVubp": it needs an instance of "App\\Entity\\Paiement" but this type has been excluded in "config/services.yaml".');
    }
}
