<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOAxNaKS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOAxNaKS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOAxNaKS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOAxNaKS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOAxNaKS\App_KernelDevDebugContainer([
    'container.build_hash' => 'OAxNaKS',
    'container.build_id' => 'fb5293bb',
    'container.build_time' => 1740997314,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOAxNaKS');
